### ISSUE TITLE
error android 11

### ISSUE THREAD

**Issue by Googler43** [Fox520/KivyPushNotifications#1]
Hello. Please tell me about the problem that I had after your video. An error occurs on android 11

5 21:02:00.533  9409  9491 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
02-15 21:02:00.533  9409  9491 I python  :    File "/home/googler/app/.buildozer/android/app/main.py", line 107, in on_start
02-15 21:02:00.533  9409  9491 I python  :  TypeError: 'java.util.Set' object is not iterable
02-15 21:02:00.534  9409  9491 I python  : Python for android ended.

At the same time, there is no such problem on a phone with android 9.

**Comment by Fox520** [comment]
Hi! Not sure if this will work but try this in your `on_resume()` & `on_start()` and see what it prints
```python
print(type(bundle))
if bundle is not None:
    print(dir(bundle))
    iter = bundle.iterator()
    while iter.hasNext():
        print(iter.next())
else:
    print("bundle is None")  
```

**Comment by Googler43** [comment]
02-24 19:18:08.019  8772  8875 I python  : <class 'jnius.reflect.android.os.Bundle'>
02-24 19:18:08.019  8772  8875 I python  : debug info----
02-24 19:18:08.019  8772  8875 I python  : ['CONTENTS_FILE_DESCRIPTOR', 'CREATOR', 'EMPTY', 'PARCELABLE_WRITE_RETURN_VALUE', '__class__', '__cls_storage', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__javaclass__', '__javaconstructor__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__pyx_vtable__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'classLoader', 'clear', 'clone', 'containsKey', 'deepCopy', 'describeContents', 'empty', 'equals', 'filterValues', 'finalize', 'forPair', 'get', 'getBinder', 'getBoolean', 'getBooleanArray', 'getBundle', 'getByte', 'getByteArray', 'getChar', 'getCharArray', 'getCharSequence', 'getCharSequenceArray', 'getCharSequenceArrayList', 'getClass', 'getClassLoader', 'getDouble', 'getDoubleArray', 'getFloat', 'getFloatArray', 'getIBinder', 'getInt', 'getIntArray', 'getIntegerArrayList', 'getLong', 'getLongArray', 'getParcelable', 'getParcelableArray', 'getParcelableArrayList', 'getSerializable', 'getShort', 'getShortArray', 'getSize', 'getSizeF', 'getSparseParcelableArray', 'getString', 'getStringArray', 'getStringArrayList', 'hasFileDescriptors', 'hashCode', 'identityHashCode', 'isEmpty', 'isParcelled', 'keySet', 'notify', 'notifyAll', 'parcelled', 'putAll', 'putBinder', 'putBoolean', 'putBooleanArray', 'putBundle', 'putByte', 'putByteArray', 'putChar', 'putCharArray', 'putCharSequence', 'putCharSequenceArray', 'putCharSequenceArrayList', 'putDouble', 'putDoubleArray', 'putFloat', 'putFloatArray', 'putIBinder', 'putInt', 'putIntArray', 'putIntegerArrayList', 'putLong', 'putLongArray', 'putParcelable', 'putParcelableArray', 'putParcelableArrayList', 'putParcelableList', 'putSerializable', 'putShort', 'putShortArray', 'putSize', 'putSizeF', 'putSparseParcelableArray', 'putString', 'putStringArray', 'putStringArrayList', 'readFromParcel', 'remove', 'setClassLoader', 'setDefusable', 'size', 'toString', 'unparcel', 'wait', 'writeToParcel']
02-24 19:18:08.019  8772  8875 I python  :  Traceback (most recent call last):
02-24 19:18:08.020  8772  8875 I python  :    File "/home/googler/app/.buildozer/android/app/main.py", line 132, in <module>
02-24 19:18:08.020  8772  8875 I python  :    File "/home/googler/app/.buildozer/android/platform/build-arm64-v8a/build/python-installs/gipci/kivy/app.py", line 854, in run
02-24 19:18:08.020  8772  8875 I python  :    File "kivy/_event.pyx", line 707, in kivy._event.EventDispatcher.dispatch
02-24 19:18:08.021  8772  8875 I python  :    File "/home/googler/app/.buildozer/android/app/main.py", line 108, in on_start
02-24 19:18:08.021  8772  8875 I python  :  AttributeError: 'android.os.Bundle' object has no attribute 'iterator'
02-24 19:18:08.021  8772  8875 I python  : Python for android ended.

**Comment by Fox520** [comment]
Thanks, do try the following. Adapted from [here](https://github.com/bendemott/PyJnius-Android-Adb-Examples/blob/master/jnius_test2.py#L100)
```python
# Object[] my_keys = bundle.keySet().toArray()
my_keys = bundle.keySet().toArray()
print(type(my_keys))
try:
    # for(Object key: my_keys)
    for key in my_keys:
        value = bundle.get(key)

except Exception as e:
    print(e)
    print("Advanced for-loop failed, attempting simple for-loop")
    
    # for(int index=0; index < my_keys.length; index++)
    for index in range(len(my_keys)):
        key = my_keys[index]
        value = bundle.get(key)
```

**Comment by Googler43** [comment]
I tried the option that you suggested. got an error

02-25 14:40:16.235 14026 14084 I python  :  AttributeError: 'NoneType' object has no attribute 'keySet'
02-25 14:40:16.235 14026 14084 I python  : Python for android ended.


I inserted before the error 
`print(dir(bundle))`
got the following

['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

        PythonActivity = autoclass('org.kivy.android.PythonActivity')
        bundle = PythonActivity.mIntentBundle
        my_keys = bundle.keySet().toArray()
        print(type(my_keys))
        try:
            # for(Object key: my_keys)
            for key in my_keys:
                value = bundle.get(key)

        except Exception as e:
            print(e)
            print("Advanced for-loop failed, attempting simple for-loop")

            # for(int index=0; index < my_keys.length; index++)
            for index in range(len(my_keys)):
                key = my_keys[index]
                value = bundle.get(key)

I'm sorry, maybe I'm asking stupid questions, it's all because I don't understand how Java and Python work together in this situation

**Comment by Fox520** [comment]
No worries, it should be like this
```python
PythonActivity = autoclass('org.kivy.android.PythonActivity')
bundle = PythonActivity.mIntentBundle

if bundle is not None: # This was missing
    my_keys = bundle.keySet().toArray()
    print(type(my_keys))
    try:
        for key in my_keys:
            value = bundle.get(key)
    except Exception as e:
        print(e)
        print("Advanced for-loop failed, attempting simple for-loop")
    
        for index in range(len(my_keys)):
            key = my_keys[index]
            value = bundle.get(key)
```

**Comment by Googler43** [comment]
It works, thanks
I suppose you also need to correct in main.py
